### ISSUE TITLE
Hard lock when fighting black giants in Kourend

### ISSUE THREAD

**Issue by SirFancyBacon** [MakingStan/Oof-Sound#5]
Steps to reproduce:

Go kill Black Demons while getting hit with protect from melee on; wait until game locks up (will lock up within 40 minutes; typically within 20)

**Comment by MakingStan** [comment]
Hello!

So it will constantly say oof?
What does it exactly do?

**Comment by SirFancyBacon** [comment]
> Hello!
> 
> So it will constantly say oof? What does it exactly do?

No, the client will freeze, visuals and sounds do not up date.

**Comment by MakingStan** [comment]
I don't think that's on my plug-in. It might just be a bug in runelite.

**Comment by SirFancyBacon** [comment]
Removing your plugin solved the crash, I am no programmer but the debug console complained about an improper use of audio.

I use Linux if that matters.

**Comment by MakingStan** [comment]
Could you give the full error log?

**Comment by MakingStan** [comment]
Closing this issue because of no response.
